684-0035016581353d7f.js:1 Error submitting score to global leaderboard: FirebaseError: Missing or insufficient permissions. push.6905.window.console.error @ 684-0035016581353d7f.js:1Understand this error firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel?VER=8&database=projects%2Fretrotypewave%2Fdatabases%2F(default)&gsessionid=plgmMRkXZOY-mgi_9K8_csarLrDriPhnzFpskHvy-oU&SID=LAFpxRZdIoKvnQUmrYZ7BA&RID=39993&TYPE=terminate&zx=hqzl1ipvdo1x:1
           Failed to load resource: the server responded with a status of 400 ()

Add error handling message for where if you're submitting a leaderboard name that already exists, it notifies the user that they must pick a unique username